# Definition for CI within GitLab
# Note:
#    Prefix any job name with a '.' to disable.
#


# Enable submodules
variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  BUILD32: 1


# Common definitions for the jobs
.common: &common
  before_script:
    - git submodule sync ci
    - git submodule update --init ci
  artifacts:
    when: always
    paths:
      - artifacts
      - ci-logs
  dependencies: []


#### Documentation ####
docs-riscos:
  <<: *common
  stage: docs
  script:
    - ci/build.sh install

docs-posix:
  <<: *common
  stage: docs
  script:
    - PRINCEXML_I_HAVE_A_LICENSE=1 ./build.sh


#### Stages to execute ####
stages:
  - docs
